# Generated by Django 3.0.6 on 2020-05-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=10)),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(max_length=10)),
            ],
        ),
    ]
